JAMO_TO_COMPAT_JAMO = ['ㄱ', 'ㄲ', 'ㄴ', 'ㄷ', 'ㄸ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅃ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅉ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ', None, 'ㅥ', 'ㅦ', None, None, None, None, 'ㅀ', None, 'ㅮ', 'ㅱ', 'ㅲ', None, 'ㅳ', 'ㅄ', 'ㅴ', 'ㅵ', None, None, None, 'ㅶ', None, 'ㅷ', None, 'ㅸ', 'ㅹ', 'ㅺ', 'ㅻ', 'ㅼ', None, None, 'ㅽ', None, None, None, 'ㅾ', None, None, None, None, None, None, None, None, None, 'ㅿ', None, None, None, None, None, None, 'ㆀ', None, None, None, None, 'ㆁ', None, None, None, None, None, None, None, None, None, None, 'ㆄ', 'ㆅ', 'ㆆ', None, 'ㅧ', 'ㄵ', 'ㄶ', None, None, None, 'ㅏ', 'ㅐ', 'ㅑ', 'ㅒ', 'ㅓ', 'ㅔ', 'ㅕ', 'ㅖ', 'ㅗ', 'ㅘ', 'ㅙ', 'ㅚ', 'ㅛ', 'ㅜ', 'ㅝ', 'ㅞ', 'ㅟ', 'ㅠ', 'ㅡ', 'ㅢ', 'ㅣ', None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'ㆇ', 'ㆈ', None, None, 'ㆉ', None, None, None, None, None, None, None, None, 'ㆊ', 'ㆋ', None, 'ㆌ', None, None, None, None, None, None, None, None, None, 'ㆍ', None, None, None, None, None, None, None, None, None, 'ㄱ', 'ㄲ', 'ㄳ', 'ㄴ', 'ㄵ', 'ㄶ', 'ㄷ', 'ㄹ', 'ㄺ', 'ㄻ', 'ㄼ', 'ㄽ', 'ㄾ', 'ㄿ', 'ㅀ', 'ㅁ', 'ㅂ', 'ㅄ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ', None, None, None, 'ㅦ', 'ㅧ', 'ㅨ', None, None, None, 'ㅩ', None, 'ㅪ', None, None, None, None, 'ㅫ', None, None, None, 'ㅬ', None, 'ㅭ', None, None, 'ㅮ', 'ㅯ', None, 'ㅰ', None, None, 'ㅱ', None, None, None, 'ㅸ', 'ㅺ', 'ㅼ', None, 'ㅽ', 'ㅿ', None, None, 'ㆀ', None, 'ㆁ', 'ㆂ', 'ㆃ', None, 'ㆄ', None, None, None, None, 'ㆆ', None, None, None, None, None, 'ㅥ']

COMPAT_JAUM_TO_CHOSEONG = ['ᄀ', 'ᄁ', None, 'ᄂ', 'ᅜ', 'ᅝ', 'ᄃ', 'ᄄ', 'ᄅ', 'ꥤ', 'ꥨ', 'ꥩ', 'ꥬ', None, None, 'ᄚ', 'ᄆ', 'ᄇ', 'ᄈ', 'ᄡ', 'ᄉ', 'ᄊ', 'ᄋ', 'ᄌ', 'ᄍ', 'ᄎ', 'ᄏ', 'ᄐ', 'ᄑ', 'ᄒ']

COMPAT_MOUM_TO_JUNGSEONG = ['ᅡ', 'ᅢ', 'ᅣ', 'ᅤ', 'ᅥ', 'ᅦ', 'ᅧ', 'ᅨ', 'ᅩ', 'ᅪ', 'ᅫ', 'ᅬ', 'ᅭ', 'ᅮ', 'ᅯ', 'ᅰ', 'ᅱ', 'ᅲ', 'ᅳ', 'ᅴ', 'ᅵ']

COMPAT_JAUM_TO_JONGSEONG = ['ᆨ', 'ᆩ', 'ᆪ', 'ᆫ', 'ᆬ', 'ᆭ', 'ᆮ', 'ퟍ', 'ᆯ', 'ᆰ', 'ᆱ', 'ᆲ', 'ᆳ', 'ᆴ', 'ᆵ', 'ᆶ', 'ᆷ', 'ᆸ', 'ퟦ', 'ᆹ', 'ᆺ', 'ᆻ', 'ᆼ', 'ᆽ', 'ퟹ', 'ᆾ', 'ᆿ', 'ᇀ', 'ᇁ', 'ᇂ']

DECOMPOSE_JONGSEONG = [None, ('ᆨ', 'ᆨ'), ('ᆨ', 'ᆺ'), None, ('ᆫ', 'ᆽ'), ('ᆫ', 'ᇂ'), None, None, ('ᆯ', 'ᆨ'), ('ᆯ', 'ᆷ'), ('ᆯ', 'ᆸ'), ('ᆯ', 'ᆺ'), ('ᆯ', 'ᇀ'), ('ᆯ', 'ᇁ'), ('ᆯ', 'ᇂ'), None, None, ('ᆸ', 'ᆺ'), None, ('ᆺ', 'ᆺ'), None, None, None, None, None, None, None]

